server:
  servlet:
    context-path: /api
spring:
  application:
    name: api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      default_batch_fetch_size: 20
      format_sql: true
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      javax.persistence.schema-generation.scripts.action: create
      javax.persistence.schema-generation.scripts.create-target: schema.sql
      javax.persistence.schema-generation.create-source: metadata
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/gomdolbook
          audiences: gomdolbook
api:
  aladin:
    baseUrl: http://www.aladin.co.kr/ttb/api/
    ttbkey: ${ALADIN_TTB_KEY}
jwt:
  token:
    secret: ${JWT_SECRET}
oauth:
  github:
    clientId: ${GITHUB_ID}
    clientSecret: ${GITHUB_SECRET}
