-- 기존 테이블 삭제
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS book_meta CASCADE;
DROP TABLE IF EXISTS book_meta_collection CASCADE;
DROP TABLE IF EXISTS collection CASCADE;
DROP TABLE IF EXISTS reading_log CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 테이블 생성
CREATE TABLE book
(
    book_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_meta_id  BIGINT,
    finished_at   TIMESTAMP(6),
    readinglog_id BIGINT UNIQUE,
    started_at    TIMESTAMP(6),
    user_id       BIGINT,
    status        VARCHAR(255) CHECK (status IN ('FINISHED', 'NEW', 'READING', 'TO_READ')),
    PRIMARY KEY (book_id)
);


CREATE TABLE book_meta
(
    book_meta_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author        VARCHAR(255)  NOT NULL,
    category_name VARCHAR(255)  NOT NULL,
    cover         VARCHAR(255)  NOT NULL,
    description   VARCHAR(1000) NOT NULL,
    isbn          VARCHAR(255)  NOT NULL UNIQUE,
    pub_date      VARCHAR(255)  NOT NULL,
    publisher     VARCHAR(255)  NOT NULL,
    title         VARCHAR(255)  NOT NULL,
    PRIMARY KEY (book_meta_id)
);


CREATE TABLE book_meta_collection
(
    book_meta_collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_meta_id            BIGINT,
    collection_id           BIGINT,
    user_id                 BIGINT,
    PRIMARY KEY (book_meta_collection_id)
);


CREATE TABLE collection
(
    collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT,
    name          VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (collection_id)
);


CREATE TABLE reading_log
(
    readinglog_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rating        INTEGER,
    note          TEXT,
    summary       TEXT,
    PRIMARY KEY (readinglog_id)
);


CREATE TABLE users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email   VARCHAR(255) NOT NULL UNIQUE,
    picture VARCHAR(255) NOT NULL,
    role enum ('ADMIN','USER'),
    primary key (user_id)
);

alter table if exists book add constraint FKg54hkbxvec8ifqutqp4746ohp foreign key (book_meta_id) references book_meta;
alter table if exists book add constraint FKbrvddxu6yc8myt92lhmltdvco foreign key (readinglog_id) references reading_log;
alter table if exists book add constraint FK9cv1tt952k857xoia51k1vj12 foreign key (user_id) references users;
alter table if exists book_meta_collection add constraint FK9ao4g2t4tadtul5h8wbvr3dnu foreign key (book_meta_id) references book_meta;
alter table if exists book_meta_collection add constraint FKa2wxqw6ny7g5ax0yxk85dj18l foreign key (collection_id) references collection;
alter table if exists book_meta_collection add constraint FK6ytqo7vi8q648k9fkkegt905e foreign key (user_id) references users;
alter table if exists collection add constraint FK45y8o0xk4kptog8w86usq3yjl foreign key (user_id) references users;
