create table book
(
    book_id       bigint generated by default as identity,
    author        varchar(255),
    category_name varchar(255),
    cover         varchar(255),
    description   varchar(255),
    isbn          varchar(255),
    pub_date      varchar(255),
    publisher     varchar(255),
    title         varchar(255),
    started_at    TIMESTAMP,
    finished_at   TIMESTAMP,
    readinglog_id bigint,
    primary key (book_id)
);

create table book_collection
(
    book_collection_id bigint generated by default as identity,
    book_id            bigint,
    collection_id      bigint,
    user_id            bigint,
    primary key (book_collection_id)
);

create table collection
(
    collection_id bigint generated by default as identity,
    name          varchar(255) not null,
    user_id       bigint,
    primary key (collection_id)
);

create table reading_log
(
    readinglog_id bigint generated by default as identity,
    note1         TEXT,
    note2         TEXT,
    note3         TEXT,
    rating        integer,
    status        enum ('FINISHED','NEW','READING','TO_READ'),
    user_id       bigint,
    primary key (readinglog_id)
);

create table users
(
    user_id bigint generated by default as identity,
    email   varchar(255) not null,
    picture varchar(255) not null,
    role    enum ('ADMIN','USER'),
    primary key (user_id)
);

alter table if exists book drop constraint if exists UKgqjxn93jsf20p2nsa9o1g802;
alter table if exists book add constraint UKgqjxn93jsf20p2nsa9o1g802 unique (readinglog_id);
alter table if exists collection drop constraint if exists UKy9tqsfhcsdnb3oqmc6dmb2i1;
alter table if exists collection add constraint UKy9tqsfhcsdnb3oqmc6dmb2i1 unique (name);
alter table if exists users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists book add constraint FKbrvddxu6yc8myt92lhmltdvco foreign key (readinglog_id) references reading_log;
alter table if exists book_collection add constraint FKhrhume0ucplaek9m8pb6ild7s foreign key (book_id) references book;
alter table if exists book_collection add constraint FKka9jqqmcu25by7m32gihxb4rr foreign key (collection_id) references collection;
alter table if exists book_collection add constraint FKo3e3fm34hbvwbcft0p856dmah foreign key (user_id) references users;
alter table if exists collection add constraint FK45y8o0xk4kptog8w86usq3yjl foreign key (user_id) references users;
alter table if exists reading_log add constraint FKbecasd79ecm9vvexa47hwfepy foreign key (user_id) references users;


